[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VUE_APP_API_URL = "http://185.97.146.99:6607/api"
  VUE_APP_SOCKET_URL = "http://185.97.146.99:6607"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 